#' Clean Raw National Household Travel Survey data
#' 
#' This script is designed to clean raw data from the NHST.
#' It will prepare the data for future statistical modeling tasks
#' and visualization.
#' 
#' @author Marion Bauman

# Load necessary libraries
library(tidyverse)
library(arrow)
library(readxl)

# Read in raw data
household <- read_csv("data/raw/hhv2pub.csv")
person <- read_csv("data/raw/perv2pub.csv")
trip <- read_csv("data/raw/tripv2pub.csv")
vehicle <- read_csv("data/raw/vehv2pub.csv")
long_distance <- read_csv("data/raw/ldtv2pub.csv")

# Read in the data dictionary
data_dictionary <- read_excel("data/dictionary.xlsx")

# Map the data dictionary to more explanatory names
data_dictionary <- data_dictionary |>
    mutate(clean_name = case_when(
        NAME == "AIRSIZE" ~ "airport_size",
        NAME == "ANNMILES" ~ "annual_miles",
        NAME == "BEGTRIP" ~ "begin_trip_date",
        NAME == "BIKESHARE22" ~ "days_used_bikeshare_last_30",
        NAME == "BIKETRANSIT" ~ "days_cycled_last_30",
        NAME == "CDIVMSAR" ~ "household_grouping",
        NAME == "CENSUS_D" ~ "census_division",
        NAME == "CENSUS_R" ~ "census_region",
        NAME == "CNTTDHH" ~ "count_household_trips",
        NAME == "CNTTDTR" ~ "count_person_trips",
        NAME == "COMMERCIALFREQ" ~ "commercial_frequency_of_veh_last_30",
        NAME == "CONDNIGH" ~ "daytime_limit_driving",
        NAME == "CONDNONE" ~ "unaffected_travel",
        NAME == "CONDPUB" ~ "limited_transit_use",
        NAME == "CONDRF" ~ "limited_transit_use_noresponse",
        NAME == "CONDRIDE" ~ "requested_rides",
        NAME == "CONDRIVE" ~ "limited_driving",
        NAME == "CONDSHARE" ~ "requested_ride_shares",
        NAME == "CONDSPEC" ~ "requires_special_transport",
        NAME == "CONDTRAV" ~ "reduce_travel_disability",
        NAME == "COV1_OHD" ~ "covid_online_delivery_impact",
        NAME == "COV1_PT" ~ "covid_public_transit_impact",
        NAME == "COV1_SCH" ~ "covid_school_travel_impact",
        NAME == "COV1_WK" ~ "covid_work_travel_impact",
        NAME == "COV2_OHD" ~ "covid_online_delivery_impact_permant",
        NAME == "COV2_PT" ~ "covid_public_transit_impact_permant",
        NAME == "COV2_SCH" ~ "covid_school_travel_impact_permant",
        NAME == "COV2_WK" ~ "covid_work_travel_impact_permant",
        NAME == "DELIVER" ~ "num_online_deliveries_last_30",
        NAME == "DELIV_FOOD" ~ "num_food_deliveries_last_30",
        NAME == "DELIV_GOOD" ~ "num_goods_deliveries_last_30",
        NAME == "DELIV_GROC" ~ "num_grocery_deliveries_last_30",
        NAME == "DELIV_PERS" ~ "num_services_deliveries_last_30",
        NAME == "DRIVE" ~ "driver_status",
        NAME == "DRIVINGOCCUPATION" ~ "drive_for_work",
        NAME == "DRIVINGVEHILCE" ~ "drive_for_work_vehicle",
        NAME == "DRVRCNT" ~ "num_drivers_in_household",
        NAME == "DRVR_FLG" ~ "driver_flag",
        NAME == "DWELTIME" ~ "time_at_destination",
        NAME == "EDUC" ~ "education_level",
        NAME == "EMPLOYMENT2" ~ "hours_worked_per_week",
        NAME == "EMPPASS" ~ "employer_pays_transit",
        NAME == "ENDTIME" ~ "end_trip_time",
        NAME == "ESCOOTERUSED" ~ "days_used_scooter_last_30",
        NAME == "EXITCDIV" ~ "exit_census_division",
        NAME == "FARCDIV" ~ "farthest_census_division_traveled",
        NAME == "FARCREG" ~ "farthest_census_region_traveled",
        NAME == "FARREAS" ~ "reason_for_travel",
        NAME == "FLAG100" ~ "all_household_completed_survey",
        NAME == "FRSTHM" ~ "started_travel_at_home",
        NAME == "GASPRICE" ~ "gas_price_at_travel_time",
        NAME == "GCDTOT" ~ "great_circle_distance_traveled",
        NAME == "GCDWORK" ~ "great_circle_distance_work",
        NAME == "GCD_FLAG" ~ "great_circle_distance_longer_than_50_miles",
        NAME == "HHACCCNT" ~ "num_household_members_on_trip",
        NAME == "HHFAMINC" ~ "household_income",
        NAME == "HHFAMINC_IMP" ~ "household_income_imputed",
        NAME == "HHMEMDRV" ~ "drove_on_trip",
        NAME == "HHRELATD" ~ "household_related",
        NAME == "HHSIZE" ~ "household_size",
        NAME == "HHVEHCNT" ~ "num_vehicles_in_household",
        NAME == "HHVEHUSETIME_DEL" ~ "days_vehicle_used_deliveries_last_30",
        NAME == "HHVEHUSETIME_OTH" ~ "days_vehicle_used_other_last_30",
        NAME == "HHVEHUSETIME_RS" ~ "days_vehicle_used_ride_shares_last_30",
        NAME == "HH_HISP" ~ "hispanic",
        NAME == "HH_RACE" ~ "race",
        NAME == "HOMEOWN" ~ "own_or_rent_home",
        NAME == "HOMETYPE" ~ "home_type",
        NAME == "HOUSEID" ~ "household_id",
        NAME == "HYBRID" ~ "hybrid_vehicle",
        NAME == "INT_FLAG" ~ "international_trip",
        NAME == "LAST30_BIKE" ~ "used_bike_last_30",
        NAME == "LAST30_BKSHR" ~ "used_bikeshare_last_30",
        NAME == "LAST30_ESCT" ~ "used_e_scooter_last_30",
        NAME == "LAST30_MTRC" ~ "used_motorcycle_last_30",
        NAME == "LAST30_PT" ~ "used_public_transit_last_30",
        NAME == "LAST30_RDSHR" ~ "used_ride_share_last_30",
        NAME == "LAST30_TAXI" ~ "used_taxi_last_30",
        NAME == "LAST30_WALK" ~ "walked_last_30",
        NAME == "LDT_FLAG" ~ "long_distance_trip",
        NAME == "LD_AMT" ~ "num_used_amtrak_last_year",
        NAME == "LD_ICB" ~ "num_used_intracity_bus_last_year",
        NAME == "LD_NUMONTRP" ~ "num_people_on_long_distance_trip",
        NAME == "LOOP_TRIP" ~ "loop_trip",
        NAME == "MAINMODE" ~ "main_mode_of_transport",
        NAME == "MAKE" ~ "vehicle_make",
        NAME == "MCTRANSIT" ~ "days_used_motorcycle_last_30",
        NAME == "MEDCOND" ~ "medical_condition",
        NAME == "MEDCOND6" ~ "medical_condition_duration",
        NAME == "MRT_DATE" ~ "date_of_most_recent_trip",
        NAME == "MSACAT" ~ "metro_area_category",
        NAME == "MSASIZE" ~ "metro_area_size",
        NAME == "NONHHCNT" ~ "num_non_household_members_on_trip",
        NAME == "NTSAWAY" ~ "num_nights_away_from_home",
        NAME == "NUMADLT" ~ "num_adults_in_household",
        NAME == "NUMONTRP" ~ "num_people_on_trip",
        NAME == "ONTD_P1" ~ "person_1_on_trip",
        NAME == "ONTD_P2" ~ "person_2_on_trip",
        NAME == "ONTD_P3" ~ "person_3_on_trip",
        NAME == "ONTD_P4" ~ "person_4_on_trip",
        NAME == "ONTD_P5" ~ "person_5_on_trip",
        NAME == "ONTD_P6" ~ "person_6_on_trip",
        NAME == "ONTD_P7" ~ "person_7_on_trip",
        NAME == "ONTD_P8" ~ "person_8_on_trip",
        NAME == "ONTD_P9" ~ "person_9_on_trip",
        NAME == "ONTD_P10" ~ "person_10_on_trip",
        NAME == "ONTP_P1" ~ "person_1_on_long_distance_trip",
        NAME == "ONTP_P2" ~ "person_2_on_long_distance_trip",
        NAME == "ONTP_P3" ~ "person_3_on_long_distance_trip",
        NAME == "ONTP_P4" ~ "person_4_on_long_distance_trip",
        NAME == "ONTP_P5" ~ "person_5_on_long_distance_trip",
        NAME == "ONTP_P6" ~ "person_6_on_long_distance_trip",
        NAME == "ONTP_P7" ~ "person_7_on_long_distance_trip",
        NAME == "ONTP_P8" ~ "person_8_on_long_distance_trip",
        NAME == "ONTP_P9" ~ "person_9_on_long_distance_trip",
        NAME == "ONTP_P10" ~ "person_10_on_long_distance_trip",
        NAME == "OUTOFTWN" ~ "away_entire_day",
        NAME == "PARK" ~ "paid_for_parking_travel_day",
        NAME == "PARK2" ~ "paid_for_parking_trip",
        NAME == "PARK2_PAMOUNT" ~ "parking_cost",
        NAME == "PARK2_PAYTYPE" ~ "parking_payment_periodicity",
        NAME == "PARKHOME" ~ "pay_home_parking",
        NAME == "PARKHOMEAMT" ~ "home_parking_cost",
        NAME == "PARKHOMEAMT_PAMOUNT" ~ "home_parking_cost",
        NAME == "PARKHOMEAMT_PAYTYPE" ~ "home_parking_payment_periodicity",
        NAME == "PAYPROF" ~ "worked_last_week",
        NAME == "PERSONID" ~ "person_id",
        NAME == "PPT517" ~ "num_children_5_17",
        NAME == "PRMACT" ~ "primary_activity_not_work",
        NAME == "PROXY" ~ "proxy_respondent",
        NAME == "PSGR_FL" ~ "passenger_on_trip",
        NAME == "PTUSED" ~ "days_used_public_transit_last_30",
        NAME == "PUBTRANS" ~ "public_transit_used_on_trip",
        NAME == "QACSLAN1" ~ "non_english_language_spoken",
        NAME == "QACSLAN3" ~ "how_well_english_spoken",
        NAME == "RAIL" ~ "metro_rail_status",
        NAME == "RESP_CNT" ~ "num_respondents_in_household",
        NAME == "RET_AMZ" ~ "num_returned_amazon_dropoff_center",
        NAME == "RET_HOME" ~ "num_returned_home_pickup",
        NAME == "RET_PUF" ~ "num_returned_ups_usps_fedex",
        NAME == "RET_STORE" ~ "num_returned_store",
        NAME == "RIDESHARE22" ~ "days_used_ride_share_last_30",
        NAME == "R_AGE" ~ "respondent_age",
        NAME == "R_HISP" ~ "respondent_hispanic",
        NAME == "R_RACE" ~ "respondent_race",
        NAME == "R_RACE_IMP" ~ "respondent_race_imputed",
        NAME == "R_RELAT" ~ "respondent_relationship",
        NAME == "R_SEX" ~ "respondent_sex",
        NAME == "R_SEX_IMP" ~ "respondent_sex_imputed",
        NAME == "SAMEPLC" ~ "reason_no_travel",
        NAME == "SCHOOL1" ~ "enrolled_in_school",
        NAME == "SCHOOL1C" ~ "school_type_nontraditional",
        NAME == "SCHTRN1" ~ "school_transportation",
        NAME == "SCHTYP" ~ "school_type",
        NAME == "SEQ_TRIPID" ~ "sequential_trip_id",
        NAME == "STRATUMID" ~ "household_stratum_id",
        NAME == "STRTTIME" ~ "start_trip_time",
        NAME == "STUDE" ~ "school_program_description",
        NAME == "TAXISERVICE" ~ "days_used_taxi_last_30",
        NAME == "TDAYDATE" ~ "travel_day_date",
        NAME == "TDCASEID" ~ "trip_id",
        NAME == "TDWKND" ~ "weekend_trip",
        NAME == "TRAVDAY" ~ "travel_day_of_week",
        NAME == "TRIPID" ~ "trip_person_id",
        NAME == "TRIPPURP" ~ "trip_purpose",
        NAME == "TRNPASS" ~ "days_used_discounted_transit_last_30",
        NAME == "TRPHHVEH" ~ "vehicle_used_on_trip",
        NAME == "TRPMILES" ~ "trip_miles",
        NAME == "TRPTRANS" ~ "trip_mode",
        NAME == "TRVLCMIN" ~ "trip_duration_minutes",
        NAME == "URBAN" ~ "household_urban_classification",
        NAME == "URBANSIZE" ~ "household_urban_size",
        NAME == "URBRUR" ~ "household_urban_rural",
        NAME == "URBRUR_2010" ~ "household_urban_rural_2010",
        NAME == "USAGE1" ~ "fewer_trips_last_30",
        NAME == "USAGE2_1" ~ "fewer_trips_last_30_reason_more_deliveries",
        NAME == "USAGE2_2" ~ "fewer_trips_last_30_reason_not_feel_safe",
        NAME == "USAGE2_3" ~ "fewer_trips_last_30_reason_not_feel_clean",
        NAME == "USAGE2_4" ~ "fewer_trips_last_30_reason_not_reliable",
        NAME == "USAGE2_5" ~ "fewer_trips_last_30_reason_not_go_where_needed",
        NAME == "USAGE2_6" ~ "fewer_trips_last_30_reason_unaffordable",
        NAME == "USAGE2_7" ~ "fewer_trips_last_30_reason_health",
        NAME == "USAGE2_8" ~ "fewer_trips_last_30_reason_time",
        NAME == "USAGE2_9" ~ "fewer_trips_last_30_reason_other",
        NAME == "USAGE2_10" ~ "fewer_trips_last_30_reason_covid",
        NAME == "VEHAGE" ~ "vehicle_age",
        NAME == "VEHCASEID" ~ "vehicle_id",
        NAME == "VEHCOMMERCIAL" ~ "vehicle_used_for_commercial_purposes",
        NAME == "VEHCOM_DEL" ~ "vehicle_used_for_deliveries",
        NAME == "VEHCOM_OTH" ~ "vehicle_used_for_other",
        NAME == "VEHCOM_RS" ~ "vehicle_used_for_ride_shares",
        NAME == "VEHFUEL" ~ "vehicle_fuel_type",
        NAME == "VEHID" ~ "household_vehicle_id",
        NAME == "VEHOWNED" ~ "vehicle_owned_more_1_year",
        NAME == "VEHOWNMO" ~ "vehicle_owned_months",
        NAME == "VEHTYPE" ~ "vehicle_type",
        NAME == "VEHYEAR" ~ "vehicle_year",
        NAME == "VMT_MILE" ~ "vehicle_miles_traveled",
        NAME == "WALK" ~ "minutes_walked_from_parking",
        NAME == "WALKTRANSIT" ~ "days_walked_as_transit_last_30",
        NAME == "WEEKEND" ~ "trip_includes_weekend",
        NAME == "WHODROVE" ~ "who_drove",
        NAME == "WHODROVE_IMP" ~ "who_drove_imputed",
        NAME == "WHOMAIN" ~ "main_driver",
        NAME == "WHOPROXY" ~ "who_completed_survey",
        NAME == "WHYFROM" ~ "reason_for_travel",
        NAME == "WHYTO" ~ "reason_for_travel_to",
        NAME == "WHYTRP1S" ~ "trip_purpose",
        NAME == "WHYTRP90" ~ "trip_purpose_old_schema",
        NAME == "WKFMHM22" ~ "days_per_week_work_from_home",
        NAME == "WORKER" ~ "worker_status",
        NAME == "WKRCOUNT" ~ "num_workers_in_household",
        NAME == "WRKLOC" ~ "work_location",
        NAME == "WRKTRANS" ~ "work_transportation",
        NAME == "WTHHFIN" ~ "household_weight_7_day",
        NAME == "WTHHFIN2D" ~ "household_weight_2_day",
        NAME == "WTHHFIN5D" ~ "household_weight_5_day",
        NAME == "WTPERFIN" ~ "person_weight_7_day",
        NAME == "WTPERFIN2D" ~ "person_weight_2_day",
        NAME == "WTPERFIN5D" ~ "person_weight_5_day",
        NAME == "WTTRDFIN" ~ "trip_weight_7_day",
        NAME == "WTTRDFIN2D" ~ "trip_weight_2_day",
        NAME == "WTTRDFIN5D" ~ "trip_weight_5_day",
        NAME == "W_CANE" ~ "used_cane",
        NAME == "W_CHAIR" ~ "used_wheelchair",
        NAME == "W_NONE" ~ "no_assistance",
        NAME == "W_SCCH" ~ "used_blind_deaf_assistance",
        NAME == "W_WKCR" ~ "used_walker_crutches",
        NAME == "YOUNGCHILD" ~ "num_children_under_5",
        TRUE ~ NAME
    ))

### HOUSEHOLD DATA ############################################################
# Clean the household data
hh_dict <- data_dictionary |>
    filter(!is.na(HH)) |>
    select(NAME, TYPE, LABEL)


household <- household |>
    janitor::clean_names()

# Pivot dictionary to long format
hh_dict |>
    filter(NAME == "WTHHFIN2D")

household |> View()
