## Introduction

Americans are in constant transit, utilizing the national interstate and highway system to travel various distances. Whether commuting to work, taking vacations, visiting friends and family, transporting goods and services, or engaging in commerce, people are constantly moving. Understanding U.S. travel patterns provides essential insights into a wide range of fields including environmental protection resource allocation, urban planning, and economic trends. This research aims to understand the motivation behind American travel based on trip specifics. Specifically, we seek to predict the purpose of trips in order to understand the connection between travel details and purpose for travel.

A wide variety of industries and stakeholders are interested in understanding travel habits and the usage of American transportation networks, particularly after the disruption of the COVID-19 pandemic that began in 2020. Research applications include: pedestrian studies, bicycle studies, environmental impact, energy consumption, health, public policty, transit planning, understanding emerging travel modes, and identifying special population groups [@Compendium]. Lu and Giuliano studied the travel habits of different income and race groups across the pandemic, finding that lower income and ethnic minority groups continued to travel for work and shopping purposes. Their model using trip purpose indicated that higher-income and White populations were able to limit travel according to government restrictions, likely due to their higher resources and increased ability to work from home [@LU2023189]. Paul's dissertation studies the vehicle-sharing its equity impacts, finding that trip purpose is a significant predictor for whether private vehicles are being shared [@Paul2023].

While extensive research has been conducted into the implications of American travel habits on equity, environment, policy, and more, little research has been done on predicting *why* a person traveled based on trip-level data, without knowing the final destination. Our research aims to fill this gap by understanding the purpose of travel without geospatial information. This modeling task importantly protects individual privacy because it includes no GPS data on travel. Using travel data such as trip length, trip timing, and demographics to predict trip purpose can be useful for understanding why Americans are in transit at a given moment. This could be useful in guiding policy decisions, informing traffic patterns, improving public transportation routes, and address socioeconomic disparities in transit.